### ISSUE TITLE
Guide not matching power apps portal 

### ISSUE THREAD

**Issue by LewisGoDeploy** [MicrosoftLearning/PL-400_Microsoft-Power-Platform-Developer#68]
## Lab: 5
Exercise 3
### Task: 2

Description of issue
This is no longer accurate, these options aren't listed below "advanced settings"
![image](https://user-images.githubusercontent.com/114931569/220308598-20ce10e6-0acd-45a2-a179-b9aee1426f24.png)

Following this guide, you also get an error when trying to import this solution:
![image](https://user-images.githubusercontent.com/114931569/220308708-3d6e6fc8-8f3a-4ff4-9e80-fd9cadd5fb62.png)

**Comment by LewisGoDeploy** [comment]
FYI my first screenshot is from this guide. The second screenshot is from my PC.

**Comment by julians1966** [comment]
This is because you imported the solution as an unmanaged solution the first time.
Now that you are importing a managed solution, the panel is offering to convert the unmanaged solution to a managed solution

If you had imported the solution as a managed solution the first time, the second import will offer the Update/Upgrade options

**Comment by skulthm-ms** [comment]
Thank you Julian. I hope this answered your question Lewis.
