### ISSUE TITLE
Unable to publish to azure function

### ISSUE THREAD

**Issue by mhykgyver** [MicrosoftLearning/PL-400_Microsoft-Power-Platform-Developer#76]
# Module: 10
#### Task: 3.1

Description of issue
Cannot publish to Azure from Visual Studio

Repro steps:

1. Follow the steps until Exercise 3, Task 3.1

![Error_VS_Publish_2](https://github.com/MicrosoftLearning/PL-400_Microsoft-Power-Platform-Developer/assets/12806459/bbdd274e-6431-48d9-af02-42c71ee77877)

**Comment by julians1966** [comment]
I can see that you have selected Azure Container when publishing to Azure.
You should have selected Azure Function App (Windows).

**Comment by julians1966** [comment]
I have tested this lab today and did not get this error. 
The steps in this lab have been updated to create the Function App in the Azure portal rather than from Visual Studio. Creating the Function App in Visual Studio often leads to issues so this change should solve many of the problems students experience.

**Comment by fuau** [comment]
Done this lab last week make sure you are following the steps exactly as they tell you with the right Dot net version and selection Azure Functions, and it should Publish.

Good Luck

**Comment by julians1966** [comment]
PR #77 changes how the Function App is created to prevent issues such as this arising
